name = "class-pets-api"
main = "src-server/index.js"
compatibility_date = "2024-03-01"
routes = [
  { pattern = "www.banjiyangchong.tech/api/*", zone_name = "banjiyangchong.tech" },
]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "class_pets_db"
database_id = "413950c7-1d1e-4c2e-b012-82b14c3c1f1a"
preview_database_id = "413950c7-1d1e-4c2e-b012-82b14c3c1f1a"
